app/API/urls.py
from django.urls import path
from API.views import API_Rate_View
from API.views import API_Rate_Details_View

urlpatterns = [
    path("retes/", API_Rate_View.as_view(), name="api-link"),
    path("retes/<int:pk>/", API_Rate_Details_View.as_view(), name="api-link"),
]

app/accounts/urls.py
from django.urls import path
from accounts.views import MyProfileView
from accounts.views import SingUpView
from accounts.views import ActivateUpView

app_name = 'accounts'

urlpatterns = [
    path("my-profile/<int:pk>", MyProfileView.as_view(), name='my-profile'),
    path('sing-up/',SingUpView.as_view(), name='sing-up-link' ),
    path('/activate/<uuid:username>/',ActivateUpView.as_view(), name='activate-link' ),

]

app/currency/urls.py
from django.urls import path
from currency.views import RateListView
from currency.views import RateDetailsView
from currency.views import RateUpdateView
from currency.views import RateDeleteView
from currency.views import RateCreateView
from currency.views import GenPassword
from currency.views import SendMailView
from currency.views import AdView

urlpatterns = [
    path("rate-list/", RateListView.as_view(), name='rate-list-link'),
    path("rate-details/<int:pk>", RateDetailsView.as_view(), name='rate-details-link'),
    path("rate-update/<int:pk>", RateUpdateView.as_view(), name='rate-update-link'),
    path("rate-delete/<int:pk>", RateDeleteView.as_view(), name='rate-delete-link'),
    path("rate-create/", RateCreateView.as_view(), name='rate-create-link'),
    path("gen/", GenPassword.as_view(),name='gen-password-link'),
    # path("contact-us/", Contact_UsView.as_view(), name='contact-us-link'),
    path("send-mail/", SendMailView.as_view(), name='send-mail-link'),
    path("advertisment/", AdView.as_view(), name='ad-link'),
]

app/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from currency.views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", HomeView.as_view(), name='index-link'),

    path('rate/', include('currency.urls')),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('api/', include('API.urls')),

    # # API
    # path("rates_list_api_example/", rates_list_api_example)
]

app/currency/models.py
from django.db import models


class Rate(models.Model):
    sale = models.DecimalField(max_digits=5, decimal_places=2)  # 123.55
    buy = models.DecimalField(max_digits=5, decimal_places=2)  # 123.55
    cread = models.DateTimeField(auto_now_add=True)
    source = models.CharField(max_length=10)
    type = models.CharField(max_length=8)


class SendMailModels(models.Model):
    email_to = models.EmailField(max_length=30)
    subject = models.CharField(max_length=126)
    body = models.CharField(max_length=2056)
    create = models.DateTimeField(auto_now_add=True)

class TimePage(models.Model):
    cread = models.DateTimeField(auto_now_add=True)
    status_code = models.PositiveSmallIntegerField()
    path = models.CharField(max_length=256)
    response_time = models.PositiveSmallIntegerField(help_text ="in seconds")

class AdPage(models.Model):
    cread = models.DateTimeField(auto_now_add=True)
    status_code = models.PositiveSmallIntegerField()
    num = models.CharField(max_length=16)

app/currency/forms.py
from django import forms
from currency.models import Rate
from currency.models import SendMailModels

class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'buy',
            'sale',
            'source',
            'type',
        )


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = SendMailModels
        fields = (
            "email_to",
            "subject",
            "body",
        )

app/currency/views.py
# import settings.settings
from currency.models import Rate
from currency.models import SendMailModels
from currency.forms import RateForm
from django.views.generic import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from django.views.generic import CreateView
# from django.views.generic import View
# from django.http import HttpResponse
from django.urls import reverse_lazy
from currency.utils import gen_password


class HomeView(TemplateView, ):
    template_name = "index.html"


class Page2View(TemplateView):
    template_name = "page2.html"


class RateListView(ListView):
    # queryset = Rate.objects.all()
    model = Rate
    template_name = 'rateList.html'

    # def get(self, request, *args, **kwargs):
    #     print("*"*10)
    #     print(request.COOKIES)
    #     print("*" * 10)
    #     return super().get(request, *args, **kwargs)


class RateDetailsView(DetailView):
    model = Rate
    template_name = "rateDetails.html"


class RateUpdateView(UpdateView):
    model = Rate
    form_class = RateForm
    success_url = reverse_lazy('rate-list-link')
    template_name = "rateUpdate.html"


class RateDeleteView(DeleteView):
    model = Rate
    success_url = reverse_lazy('rate-list-link')
    template_name = "rateDelete.html"


class RateCreateView(CreateView):
    model = Rate
    form_class = RateForm
    success_url = reverse_lazy('rate-list-link')
    template_name = "rateCreate.html"


class GenPassword(TemplateView):
    template_name = 'gen.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            password_len = int(self.request.GET.get('pl'))
        except TypeError:
            password_len = 10

        context['password1'] = gen_password(password_len)  # 1234567890duas

        return context


class SendMailView(CreateView):
    model = SendMailModels
    fields = (
        "email_to",
        "subject",
        "body",
    )
    success_url = reverse_lazy('index-link')
    template_name = "Send_mail.html"

    def form_invalid(self, form):
        print("форма не корректна")
        return self.render_to_response(self.get_context_data(form=form))

    def form_valid(self, form):
        from currency.tasks import send_mail_task
        # s = form.cleaned_data['subject']
        send_mail_task.delay(form.cleaned_data['subject'], form.cleaned_data['body'], form.cleaned_data['email_to'])
        # send_mail_task.apply_async(args=(form.cleaned_data['subject'],form.cleaned_data['body'],form.cleaned_data['email_to']))
        return super().form_valid(form)


# def rates_list_api_example(request):
#     import json
#     rates = Rate.objects.all()
#     result = []
#     for i in rates:
#         result.append(
#             {
#                 "id": i.id,
#                 "type": i.type,
#                 "buy": float(i.buy),
#                 "sale": float(i.sale),
#             }
#         )
#
#     return HttpResponse(json.dumps(result), content_type="application/json")


class AdView(TemplateView):
    template_name = "ad.html"

app/currency/templates/Send_mail.html
{% extends 'base.html' %}

{% block main_content %}
Contact us:
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <br><br>
    <button type="submit">Send</button>
</form>
{% endblock %}

app/currency/templates/ad.html
{% extends 'base.html'%}


{% block main_content %}
<br><a href="{% url 'index-link' %}?gclid=1">Link 1</a><br>
<br><a href="{% url 'index-link' %}?gclid=2">Link 2</a><br>
<br><a href="{% url 'index-link' %}?gclid=3">Link 3</a><br>


{% endblock %}

app/currency/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>

<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="navbar-brand" href="{% url 'index-link' %}">Home</a>
            <a class="navbar-brand" href="{% url 'rate-list-link' %}">Rate List</a>
            <a class="navbar-brand" href="{% url 'rate-create-link' %}">Rate Create</a>
            <a class="navbar-brand" href="{% url 'gen-password-link' %}">Generator Password</a>
            <a class="navbar-brand" href="{% url 'send-mail-link' %}">Send mail</a>
            <a class="navbar-brand" href="{% url 'ad-link' %}">ad</a>
        </li>
    </ul>
    {% if not request.user.is_authenticated %}
    <ul class="navbar-nav mr-left">
        <li class="nav-item active">
            <a class="navbar-brand" href="{% url 'login' %}">Login</a>
            <a class="navbar-brand" href="{% url 'accounts:sing-up-link' %}">SingUp</a>
        </li>
    </ul>
    {% else %}
    <ul class="navbar-nav mr-left">
        <li class="nav-item active">
            <a class="navbar-brand" href="{% url 'accounts:my-profile' request.user.id %}">My profile</a>
            <a class="navbar-brand" href="{% url 'password_change'%}">password_change</a>
            <a class="navbar-brand" href="{% url 'logout'%}">LogOut</a>
        </li>
    </ul>
    {% endif %}

</nav>

{% block main_content %}

{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"></script>

</body>
</html>

app/currency/templates/gen.html
{% extends 'base.html'%}


{% block main_content %}


password: {{password1}}
{% endblock %}

app/currency/templates/index.html
{% extends 'base.html' %}

{% block main_content %}
<h1>Привет это начальная страница</h1>
{% endblock %}

app/currency/templates/page2.html
{% extends 'base.html' %}

{% block main_content %}
<h1>Привет от 2 страницы</h1>
{% endblock %}

app/currency/templates/rateCreate.html
{% extends 'base.html' %}

{% block main_content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <br><br>
    <button type="submit">Send</button>
</form>
{% endblock %}

app/currency/templates/rateDelete.html
{% extends 'base.html' %}

{% block main_content %}
Вы уверенны, что хотите удалить объект {{object.id}} ?
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <br><br>
    <button type="submit">Удалить</button>
</form>
{% endblock %}

app/currency/templates/rateDetails.html
{% extends 'base.html' %}

{% block main_content %}

Rate Details:</br>
ID: {{object.id}}</br>
Sale: {{object.sale}}</br>
Buy: {{object.buy}}</br>
Cread: {{object.cread}}</br>
Source: {{object.source}}</br>
Type: {{object.type}}</br>

{% endblock %}

app/currency/templates/rateList.html
{% extends 'base.html' %}

{% block main_content %}
<div class="container">
    <table class="table" border="2">
        <tr>
            <th>ID</th>
            <th>sale</th>
            <th>buy</th>
            <th>type</th>
            <th>Details</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        {% for rate in rate_list %}
        <tr>
            <td>{{rate.id}}</td>
            <td>{{rate.sale}}</td>
            <td>{{rate.buy}}</td>
            <td>{{rate.type}}</td>
            <td><a href="{% url 'rate-details-link' pk=rate.pk %}">Details</a></td>
            <td><a href="{% url 'rate-update-link' pk=rate.pk %}">Update</a></td>
            <td><a href="{% url 'rate-delete-link' pk=rate.pk %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

app/currency/templates/rateUpdate.html
{% extends 'base.html' %}

{% block main_content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <br><br>
    <button type="submit">Send</button>
</form>
{% endblock %}